### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by felixxsr** [Jannik-Schilling/generate_swmm_inp#48]
Hello Jannik, first of all I would like to thank you for this amazing tool! My question is related to a error that I am getting when I try to import an specific .INP to QGIS. Can you help me? I get the following error message:

style files saved to folder C:\Users\gabri\Desktop\Teste
reading inp ...
generating options file ...
generating inflows file ...
generating patterns file ...
generating quality file ...
generating raingages file ...
Traceback (most recent call last):
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\generate_swmm_import_inp_file.py", line 704, in processAlgorithm
geodata_driver_num,
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 223, in create_layer_from_table
data_df.apply(lambda x: create_feature_from_df(x, pr, geom_type), axis =1)
File "C:\PROGRA1\QGIS31.18\apps\Python37\lib\site-packages\pandas\core\frame.py", line 6878, in apply
return op.get_result()
File "C:\PROGRA1\QGIS31.18\apps\Python37\lib\site-packages\pandas\core\apply.py", line 186, in get_result
return self.apply_standard()
File "C:\PROGRA1\QGIS31.18\apps\Python37\lib\site-packages\pandas\core\apply.py", line 296, in apply_standard
values, self.f, axis=self.axis, dummy=dummy, labels=labels
File "pandas_libs\reduction.pyx", line 618, in pandas._libs.reduction.compute_reduction
File "pandas_libs\reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 223, in
data_df.apply(lambda x: create_feature_from_df(x, pr, geom_type), axis =1)
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 172, in create_feature_from_df
f.setGeometry(df.geometry)
TypeError: QgsFeature.setGeometry(): arguments did not match any overloaded call:
overload 1: argument 1 has unexpected type 'QVariant'
overload 2: argument 1 has unexpected type 'QVariant'

Thank you very much!

**Comment by Jannik-Schilling** [comment]
Hello felixxsr,
thanks for reporting this. Apparently I forgot to write an exception for this case: it seems like there are no symbol coordinates for the rain gage(s) in your inp file. 
A quick solution: you can add a [SYMBOLS] section at the end of the inp file if it is not already there and then you add (any) coordinates for each rain gage in your model, e.g. for a rain gage with the name 'R_1':

```
[SYMBOLS]
;;Gage           X-Coord            Y-Coord        
;;-------------- ------------------ ------------------
R_1             309239.059         5998337.220
```

**Comment by Jannik-Schilling** [comment]
fix: [68a15c5](https://github.com/Jannik-Schilling/generate_swmm_inp/commit/68a15c5403f2be779a6bcef8a391161fa47730d3)

**Comment by Jannik-Schilling** [comment]
still needs some testing

**Comment by felixxsr** [comment]
Thank you very much for your fast reply, I am writting my thesis now so I really thank you for the help haha ! 

I added the coordiantes to the Rain Gauge and it runs with no error message. But it is for like 30 min running to generate the subcatchments (I have like 80.000 subcatchments maybe thats why is taking long?)

I will in let it running overnight and let you know if it worked tomorrow! :)

![running](https://user-images.githubusercontent.com/120743190/208176895-0b82ac02-5820-41f4-b980-c8ce9fa78d46.jpg)

**Comment by Jannik-Schilling** [comment]
> But it is for like 30 min running to generate the subcatchments (I have like 80.000 subcatchments maybe thats why is taking long?)

yep, 80000 will take some time...especially, if you have a lot of vertices for complex subcatchment polygons.

Good luck!

**Comment by felixxsr** [comment]
![Worked!](https://user-images.githubusercontent.com/120743190/208197122-a0e3c866-5348-4dee-92bc-b896e052409a.jpg)
 
It worked !! Thank you so much :D

**Comment by Jannik-Schilling** [comment]
seems to be fixed
