### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by MaciejKolodziejski** [Jannik-Schilling/generate_swmm_inp#6]
Hi
Sorry to be impatient.
When can the tutorial be expected?
Maciej

**Comment by Jannik-Schilling** [comment]
Hello Maciej,
At the moment, there are several tasks, which I´m working on (see other issues). An instructional text is in progress. However I cannot predict when it will be published. 

For urgent questions on "how to start" you can write me an email ( -> jannik.schilling[at]uni-rostock.de ). 

Kind Regards 
Jannik

**Comment by Jannik-Schilling** [comment]
- [x] make instructional video (not uploaded yet..)
- [ ] upload video :-)
- [ ] write documentation for data in tables
- [ ] write documentation for data in shapefiles if their format is different from SWMM´s user interface.

**Comment by Jannik-Schilling** [comment]
Update: https://github.com/Jannik-Schilling/generate_swmm_inp/blob/dev_v_0_15/documentation/g_s_i_documentation_v_0_1.pdf

... will be merged soon (hopefully)

**Comment by Jannik-Schilling** [comment]
https://github.com/Jannik-Schilling/generate_swmm_inp/blob/main/documentation/g_s_i_documentation_v_0_2.pdf

**Comment by danieles-93** [comment]
Hola, tengo un error que no he podido solucionar, 

reading shapfiles
done
reading tables
done
preparing data for input file
Traceback (most recent call last):
File "C:/Users/danie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\generate_swmm_inp_file.py", line 438, in processAlgorithm
junctions_df['X_Coord'],junctions_df['Y_Coord'] = get_coords_from_geometry(junctions_df)
TypeError: cannot unpack non-iterable NoneType object

La ejecución falló después de 0.02 segundos

se trata de las coordenadas pero no logro resolverlo

agradecería  mucho tu ayuda


![Error](https://user-images.githubusercontent.com/98361171/150876160-6325cd20-d810-4781-b9ed-5c557c61d52f.png)

**Comment by Jannik-Schilling** [comment]
Hola @danieles-93 , por favor escribe un nuevo "issue". Esto aqui es sólo para preguntas sobre el tutorial.

**Comment by maheswarialwar** [comment]
sir I am doing PhD work using SWMM model. I am using Generate SWMM INP  I received the following error for Conduit 
![Error occurred in cresting conduit]
(https://user-images.githubusercontent.com/105992496/169680960-eb4a577f-60ab-4587-836d-095aeef94ef5.jpg)

**Comment by maheswarialwar** [comment]
column can not be kept as shape as I am using the shape file to create the layer. I try to use the standard document given by you, but I was not able to change the coordinate Reference system. so can you please help me in this.

**Comment by Jannik-Schilling** [comment]
you don´t need to save the attribute table in another file. You simply need a column with the name "Shape" containing strings... There´s no need for a change in coordinate reference system.

**Comment by felixxsr** [comment]
Hello Jannik, first of all I would like to thank you for this amazing tool!  My question is related to a error that I am getting when I tryt yo import the .INP to QGIS. Can you help me? I get the following error message:

style files saved to folder C:\Users\gabri\Desktop\Teste
reading inp ...
generating options file ...
generating inflows file ...
generating patterns file ...
generating quality file ...
generating raingages file ...
Traceback (most recent call last):
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\generate_swmm_import_inp_file.py", line 704, in processAlgorithm
geodata_driver_num,
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 223, in create_layer_from_table
data_df.apply(lambda x: create_feature_from_df(x, pr, geom_type), axis =1)
File "C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\pandas\core\frame.py", line 6878, in apply
return op.get_result()
File "C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\pandas\core\apply.py", line 186, in get_result
return self.apply_standard()
File "C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\pandas\core\apply.py", line 296, in apply_standard
values, self.f, axis=self.axis, dummy=dummy, labels=labels
File "pandas\_libs\reduction.pyx", line 618, in pandas._libs.reduction.compute_reduction
File "pandas\_libs\reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 223, in <lambda>
data_df.apply(lambda x: create_feature_from_df(x, pr, geom_type), axis =1)
File "C:/Users/gabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp\g_s_read_write_data.py", line 172, in create_feature_from_df
f.setGeometry(df.geometry)
TypeError: QgsFeature.setGeometry(): arguments did not match any overloaded call:
overload 1: argument 1 has unexpected type 'QVariant'
overload 2: argument 1 has unexpected type 'QVariant'


Thank  you very much!
